import { useState } from "react";
import Navbar from "../Navbar";
import Footer from "../Footer";

const rewardsTiers = [
    { assets: "$0+", rate: "2%" },
    { assets: "$1,000+", rate: "2.5%" },
    { assets: "$50,000+", rate: "3%" },
    { assets: "$100,000+", rate: "4%" },
];

const onePerks = [
    { stat: "$0", label: "Zero trading fees", sub: "on first $500/mo in trades, a spread applies" },
    { stat: "3.5%", label: "Unlimited USDC rewards", sub: "on all your USDC" },
    { stat: "5%", label: "More staking rewards", sub: "on ETH, SOL, and other eligible assets" },
    { stat: "$120", label: "Transaction credits on Base", sub: "$10/mo in sponsored smart wallet gas on Base" },
];

const amexBenefits = [
    "Retail Protection",
    "Extended Warranty",
    "Return Protection",
    "Amex Offers",
    "Amex Experiences™",
    "Worldwide Car Rental Loss & Damage Insurance",
    "Trip Cancellation/Trip Interruption",
    "Lost or Damaged Luggage Insurance",
    "Roadside Assistance",
    "Emergency Assistance",
];

const faqs = [
    {
        q: "Do I need to be a Coinbase One member to get the card?",
        a: "The Coinbase One Card is exclusively available to Coinbase One members at no added charge — starting with our Basic annual plan. The card is also available with all Coinbase One Preferred and Premium membership plans. The Coinbase One Card is available only within the United States, excluding U.S. territories.",
    },
    {
        q: "How do the bitcoin back rewards rates work?",
        a: "Cardholders can earn up to 4% bitcoin back on their purchases. The more assets you hold on Coinbase the higher your rewards rate. You can hold any asset including USDC or USD to qualify.",
    },
    {
        q: "Are bitcoin back rewards reported on my 1099 tax forms?",
        a: "No, they are not. Bitcoin back rewards earned on purchases made with your Coinbase One Card will not be reflected in the 1099 Tax forms generated by Coinbase. If you sell your bitcoin rewards, taxes might apply.",
    },
    {
        q: "Will my crypto assets be lent out or rehypothecated to fund Coinbase One Card rewards?",
        a: "No. Your crypto remains yours, always. We never lend or take action with your assets without your permission.",
    },
];

function FAQItem({ q, a }) {
    const [open, setOpen] = useState(false);
    return (
        <div className="border-b border-white/10 py-5">
            <button onClick={() => setOpen(!open)} className="flex items-center justify-between w-full text-left">
                <span className="text-sm font-semibold text-white">{q}</span>
                <svg className={`w-5 h-5 text-gray-400 flex-shrink-0 transition-transform ${open ? "rotate-180" : ""}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5" />
                </svg>
            </button>
            {open && <p className="mt-3 text-sm text-gray-400 leading-relaxed">{a}</p>}
        </div>
    );
}

export default function CreditCard() {
    return (
        <div className="min-h-screen flex flex-col bg-[#07080a] text-white">
            <Navbar />

            {/* Hero — centered layout matching real page */}
            <section className="relative overflow-hidden pt-32 pb-0 px-6 text-center">
                {/* Subtle glow */}
                <div className="absolute inset-0 pointer-events-none">
                    <div className="absolute top-1/3 left-1/2 -translate-x-1/2 w-[700px] h-[400px] bg-blue-600/10 blur-[120px] rounded-full" />
                </div>

                <div className="relative max-w-3xl mx-auto">
                    {/* Label */}
                    <p className="text-sm font-semibold tracking-widest text-gray-400 uppercase mb-5">
                        coinbase <span className="text-white font-bold">ONE CARD</span>
                    </p>

                    {/* Heading */}
                    <h1 className="text-5xl md:text-6xl font-extrabold leading-[1.05] mb-6">
                        Earn up to 4% bitcoin back<br />on every purchase.
                    </h1>

                    <p className="text-gray-400 text-sm mb-3">Available in the Coinbase mobile app</p>
                    <p className="text-xs text-gray-600 mb-10">Terms apply</p>

                    <a
                        href="https://www.coinbase.com/en-gb/creditcard"
                        target="_blank"
                        rel="noreferrer"
                        className="inline-block bg-blue-600 hover:bg-blue-700 text-white font-semibold px-8 py-3.5 rounded-full transition-colors text-sm mb-14"
                    >
                        Get Started
                    </a>
                </div>

                {/* Card image — full width centered, bleeds below */}
                <div className="relative max-w-2xl mx-auto">
                    <img
                        src="https://d1dwhf283nul1c.cloudfront.net/ui_components_asset/8249ef55-65c6-4497-811d-784bf54caace.webp"
                        alt="Coinbase One Card"
                        className="w-full object-contain drop-shadow-2xl"
                    />
                </div>
            </section>

            {/* Hold more, earn more */}
            <section className="py-20 px-6 bg-[#0d0f12]">
                <div className="max-w-5xl mx-auto text-center mb-14">
                    <h2 className="text-3xl font-bold mb-4">Hold more. Earn more.</h2>
                    <p className="text-gray-400 text-sm max-w-xl mx-auto">
                        The more assets you hold on Coinbase, the more bitcoin rewards you earn on your purchases.¹
                    </p>
                </div>
                <div className="max-w-3xl mx-auto grid grid-cols-2 md:grid-cols-4 gap-4">
                    {rewardsTiers.map((t, i) => (
                        <div key={i} className="bg-white/5 border border-white/10 rounded-2xl p-6 text-center hover:bg-white/10 transition-colors">
                            <p className="text-2xl font-extrabold text-orange-400 mb-1">{t.rate}</p>
                            <p className="text-xs text-gray-400">bitcoin back</p>
                            <p className="text-xs text-gray-500 mt-2">{t.assets} assets</p>
                        </div>
                    ))}
                </div>
            </section>

            {/* Coinbase One section */}
            <section className="py-20 px-6">
                <div className="max-w-6xl mx-auto">
                    <h2 className="text-3xl font-bold text-center mb-4">Maximize your experience with Coinbase One.</h2>
                    <p className="text-center text-gray-400 text-sm mb-14 max-w-xl mx-auto">
                        This credit card is exclusively available to Coinbase One members at no added charge. Annual membership starts at $49.99 per year.
                    </p>
                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
                        {onePerks.map((p, i) => (
                            <div key={i} className="bg-white/5 border border-white/10 rounded-2xl p-6 hover:bg-white/10 transition-colors">
                                <p className="text-3xl font-extrabold text-white mb-2">{p.stat}</p>
                                <p className="text-sm font-semibold text-gray-200 mb-1">{p.label}</p>
                                <p className="text-xs text-gray-500 leading-relaxed">{p.sub}</p>
                            </div>
                        ))}
                    </div>

                    {/* Bitcoin drops promo */}
                    <div className="mt-10 rounded-2xl border border-orange-500/20 bg-orange-500/5 p-8 text-center">
                        <p className="text-lg font-bold text-white mb-2">Your chance to win up to $100K in Bitcoin every month.</p>
                        <p className="text-sm text-gray-400 mb-2">Earn an entry for every $100 spent with the Coinbase One Card or traded on Coinbase. Max 25 entries.</p>
                        <a href="https://www.coinbase.com/sweepstakes/BTCdrops_rules" target="_blank" rel="noreferrer" className="text-xs text-orange-400 hover:underline">See official rules</a>
                    </div>
                </div>
            </section>

            {/* Amex benefits */}
            <section className="py-20 px-6 bg-[#0d0f12]">
                <div className="max-w-5xl mx-auto">
                    <h2 className="text-3xl font-bold text-center mb-4">Additional cardholder benefits</h2>
                    <p className="text-center text-gray-400 text-sm mb-12">
                        Gain access to more benefits through our partnership with the American Express® network.³
                    </p>
                    <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-5 gap-3">
                        {amexBenefits.map((b, i) => (
                            <div key={i} className="bg-white/5 border border-white/10 rounded-xl p-4 text-xs text-gray-300 text-center hover:bg-white/10 transition-colors">
                                {b}
                            </div>
                        ))}
                    </div>
                </div>
            </section>

            {/* Genesis Block */}
            <section className="py-20 px-6">
                <div className="max-w-6xl mx-auto grid lg:grid-cols-2 gap-14 items-center">
                    <div>
                        <h2 className="text-3xl font-bold mb-5">The Genesis Block</h2>
                        <p className="text-gray-400 leading-relaxed mb-8">
                            When Satoshi Nakamoto created the Bitcoin Genesis Block, it started a new currency, a new economy, and a new era of financial freedom. This card is etched with the original Genesis Block.
                        </p>
                        <div className="flex flex-col gap-4">
                            {[
                                { label: "MATERIAL", value: "Stainless steel" },
                                { label: "WEIGHT", value: "17 grams" },
                                { label: "PROVIDER", value: "American Express®" },
                            ].map((row, i) => (
                                <div key={i} className="flex items-center gap-4 border-b border-white/10 pb-4">
                                    <span className="text-xs font-semibold text-gray-500 uppercase tracking-widest w-24 flex-shrink-0">{row.label}</span>
                                    <span className="text-sm text-white font-medium">{row.value}</span>
                                </div>
                            ))}
                        </div>
                    </div>
                    <div className="flex justify-center lg:justify-end">
                        <img
                            src="https://ctf-images-01.coinbasecdn.net/voaboiz0ig30/2iG4spuV89MyPiqzatOqi5/ba63e0da578c892e1eaaaf2f641bf35e/StackedCrop.png"
                            alt="Coinbase Credit Card stacked"
                            className="w-full max-w-[420px] object-contain drop-shadow-2xl"
                        />
                    </div>
                </div>
            </section>

            {/* FAQs */}
            <section className="py-20 px-6 bg-[#0d0f12]">
                <div className="max-w-3xl mx-auto">
                    <h2 className="text-3xl font-bold text-center mb-12">Frequently asked questions</h2>
                    {faqs.map((faq, i) => (
                        <FAQItem key={i} q={faq.q} a={faq.a} />
                    ))}
                    <p className="text-xs text-gray-600 mt-10 leading-relaxed">
                        Coinbase One Card is offered through Coinbase, Inc. and Cardless, Inc. Cards issued by First Electronic Bank. American Express is a registered trademark of American Express and is used by the issuer pursuant to a license. The Coinbase One Card is subject to credit approval and other eligibility requirements.
                    </p>
                </div>
            </section>

            <Footer />
        </div>
    );
}
